### ISSUE TITLE
Vdieo Play But Black Screen show 

### ISSUE THREAD

**Issue by sutharmaulik** [mostafa/react-native-fullscreen-video#12]

**Comment by sutharmaulik** [comment]
Video play but But Screen show in sound get

**Comment by mostafa** [comment]
Hi,
If I can find a suitable time, I'll test it. If you can provide more info on the exact version of react-native you have used plus other pieces of libraries/software, it would be great.

**Comment by mostafa** [comment]
Finally I found some time to test the package again and it works fine. The `simple-example` is basically a video component, so you'll see a blank (black) screen before the MP4 loads and plays. I know it's a long time, but if you provide more feedback, I can help you better. I am closing this issue, feel free to re-open it if your issue is still not fixed.
